FROM docker.io/archlinux:base-devel

# Pacman
RUN sed -i 's/#Color/Color/g' /etc/pacman.conf && \
printf "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" | sudo tee -a /etc/pacman.conf && \
sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc)"/g' /etc/makepkg.conf && \
pacman -Syu --noconfirm && \
pacman -S base-devel git lib32-mesa lib32-vulkan-radeon vulkan-radeon --noconfirm && \
pacman -S steam lutris solaar --noconfirm

# AUR
RUN useradd -m --shell=/bin/bash build && usermod -L build && \
echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER build
WORKDIR /home/build
RUN git clone https://aur.archlinux.org/yay-bin.git && \
cd yay-bin && \
makepkg -si --noconfirm && \
cd .. && \
rm -drf yay-bin && \
yay -S aur/protonup-qt aur/mangohud aur/obs-vkcapture aur/protontricks aur/goverlay-bin aur/libstrangle aur/vkbasalt aur/lib32-vkbasalt --noconfirm

# Cleanup AUR
USER root
WORKDIR /
RUN  userdel -r build && \
rm -drf /home/build

# Fix ProtonupQT
RUN git clone https://github.com/DavidoTek/ProtonUp-Qt.git && \
cp ProtonUp-Qt/share/applications/net.davidotek.pupgui2.desktop /usr/share/applications/protonup-qt.desktop && \
sed -i 's,Exec=net.davidotek.pupgui2,Exec=/usr/bin/python -m pupgui2 "$@",g' /usr/share/applications/protonup-qt.desktop && \
cp -r ProtonUp-Qt/share/icons /usr/share/icons && \
rm -drf ProtonUp-QT

# Integrate make host aware of xdg-open, flatpak, and firefox
# Note: Currently xdg-open gets slightly malformed by the 'sed' operation, however I have refrained from symlinking so a clean distrobox-host-exec is installed by distrobox
RUN git clone https://github.com/89luca89/distrobox.git && \
rm -f /usr/bin/xdg-open && \
cat distrobox/distrobox-host-exec | tee /usr/bin/xdg-open && \
sed -i 's/non_interactive=0/non_interactive=1/g' /usr/bin/xdg-open && \
chmod +x /usr/bin/xdg-open && \
rm -drf distrobox