FROM docker.io/archlinux:base-devel

# Pacman
RUN sed -i 's/#Color/Color/g' /etc/pacman.conf && \
printf "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" | sudo tee -a /etc/pacman.conf && \
pacman -Syu --noconfirm && \
pacman -S base-devel git --noconfirm && \
pacman -S steam lutris solaar --noconfirm

# Enable Chaotic AUR and install mesa-git
RUN pacman-key --init
RUN pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com && \
pacman-key --lsign-key FBA220DFC880C036 && \
pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' && \
printf "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist\n" | sudo tee -a /etc/pacman.conf && \
pacman -Syu && \
pacman -S lib32-mesa-tkg-git mesa-tkg-git --noconfirm

# AUR
RUN useradd -m --shell=/bin/bash build && usermod -L build && \
echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER build
WORKDIR /home/build
RUN git clone https://aur.archlinux.org/yay-bin.git && \
cd yay-bin && \
makepkg -si --noconfirm && \
cd .. && \
rm -drf yay-bin && \
yay -S aur/protonup-qt aur/mangohud aur/obs-vkcapture aur/protontricks aur/goverlay-bin aur/libstrangle aur/vkbasalt aur/lib32-vkbasalt --noconfirm

# Cleanup AUR
USER root
WORKDIR /
RUN  userdel -r build && \
rm -drf /home/build

# Custom
RUN git clone https://github.com/DavidoTek/ProtonUp-Qt.git && \
cp ProtonUp-Qt/share/applications/net.davidotek.pupgui2.desktop /usr/share/applications/protonup-qt.desktop && \
sed -i 's,Exec=net.davidotek.pupgui2,Exec=/usr/bin/python -m pupgui2 "$@",g' /usr/share/applications/protonup-qt.desktop && \
cp -r ProtonUp-Qt/share/icons /usr/share/icons && \
rm -drf ProtonUp-QT
